### ISSUE TITLE
why only pictures? only jpg?

### ISSUE THREAD

**Issue by ivanbalashov239** [denisov/flickr-uploader-go#1]
```golang

		if strings.ToLower(filepath.Ext(path)) != ".jpg" {
			return nil
		}
``` 
i guess it's because you didn't need more than that, so my question is: How  do you think support for other formats and videos should be implemented?

- [ ] config specified file formats
- [ ] separate support for video formats
- [ ] auto split for too long videos
- [ ] support for extensions

**Comment by denisov** [comment]
Hi!

Yes you are right, I need jpg only.

I think that popular image formats can be added easily. Just replace `if` with `OR` condition. Something like that
```golang
if (strings.ToLower(filepath.Ext(path)) != ".jpg") AND ((strings.ToLower(filepath.Ext(path)) != ".png")) 
```
These extensions can be moved to config file.

I think filckr may not support some rare formats like `tiff, raw, etc..`. There is need to convert these formats before upload to flickr. "imagemagick" is good tool for image convertation

As far as videos, it seems like Filickr API doesn't support videos at all https://www.flickr.com/services/api/
